### ISSUE TITLE
Immediately exits Viber upon start on 15.04

### ISSUE THREAD

**Issue by Zeuhlord** [karas84/viberwrapper-indicator#6]
After latest updates to Ubuntu 15.04 (worked until today) your Viber Indicator for Ubuntu stopped working, you click on the icon, Viber appears then immediately closes, regular Viber works without issues. I installed from Webupd8 repository and this is the version I have:

viberwrapper-indicator                               0.1+git20141205~webupd8~0                  amd64        Wrapper Indicator for Viber Icon for Ubuntu

I understand 15.04 is still in development but I wanted to report this nevertheless.

**Comment by Zeuhlord** [comment]
After latest updates it works again, I believe you can disregard this, it was probably an issue on the development version of Ubuntu.

**Comment by hotice** [comment]
I'm having this issue too on Ubuntu 15.04: the indicator doesn't show up, the Viber window shows up for a few seconds and then it closes. This is the terminal output:
```
$ viberwrapper-indicator 
<class 'Xlib.protocol.request.QueryExtension'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/bin/viberwrapper-indicator", line 333, in run
    gtk.main_quit()
RuntimeError: called outside of a mainloop
```

**Comment by hotice** [comment]
I managed to fix this by changing:
```
if geom['width'] == 22 and geom['height'] == 22:
```
To:
```
if geom['width'] == 10 and geom['height'] == 10:
```

**Comment by hotice** [comment]
It's probably best to use this instead, which should make it work for everybody:
```
if geom['width'] == 10 and geom['height'] == 10 or geom['width'] == 22 and geom['height'] == 22:
```

**Comment by karas84** [comment]
Sorry for the late reply, been really busy at work lately. Anyway I updated the code to use the same detection method I used in my [whatsapp launcher](https://github.com/karas84/whatsapp-launcher). Unfortunately I can't test the code agaist 15.04 since I'm using the last LTS and can't upgrade. If you guys could test it for me I would appreciate it.
The new method does not use any hack to find viber (no more polling and checking geometry, that was really ugly) but asks compiz for notifications about new windows.

**Comment by hotice** [comment]
Hmm but that means it's Unity-only... while the old version was also working with other desktops that support AppIndicators, like Xfce, GNOME Classic (Flashback), elementary OS, MATE, etc...

**Comment by hotice** [comment]
I just tested it and it works on Ubuntu 15.04.

**Comment by karas84** [comment]
You are right, the thing is I started this project having unity in mind, so it felt natural to have compiz. Still I get that this way I'm leaving out a lot of non-unity users. Guess I could try to detect compiz and fallback to the "old detection method" if it's not present.

**Comment by fritzvl** [comment]
I have this issue with the latest version of wrapper with 10/22 width support in line 320. I have Viber icon in both places - in the tray and in the upper-left corner.
I'm running 15.04 on my laptop with an additional display.

**Comment by hotice** [comment]
@fritzvl could you please try downloading the latest Viber from its website and reinstall? I have a feeling that while the package version is the same, the contents are actually different.

**Comment by fritzvl** [comment]
@hotice Just reinstall Viber from the official website, and reintall .deb of viberwrapper. Problem exists.
![screenshot from 2015-05-26 21 12 11](https://cloud.githubusercontent.com/assets/459204/7819681/fb73286a-03eb-11e5-926b-35a15612fd0d.png)

**Comment by hotice** [comment]
This is one weird bug, for me it doesn't happen in either Ubuntu 15.04 or 14.04 - screenshot with both versions (14.04 is the VirtualBox window on the right): http://i.imgur.com/KU8JnjH.jpg

**Comment by hotice** [comment]
@karas84 if possible, can you please use both detection methods so it works for both Unity and non-Unity desktops, so I can update the PPA?

**Comment by hotice** [comment]
I've updated the PPA with the latest code from Git, even though it doesn't support Unity, since it looks like the old version had more bugs than the new one... this should help the dev track the bugs without having to worry about which version of the script was used. However, the latest version from Git fails in my test under Ubuntu 12.04, with the quite frequently reported "RuntimeError: called outside of a mainloop" error...

**Comment by karas84** [comment]
@hotice Thank you. I'll add the old detection method tonight or tomorrow. I'm also interested in   your test under 12.04. Am I wrong or that version supported system tray icons? That "could" be a starting point. Moreover my intention was to provide a workaround for those systems where the system tray was not supported, so if that's the case than I'd prefer not to address the issue.
Finally, thank you for providing a PPA for my work.

**Comment by karas84** [comment]
I've reintroduced the old detection method in case compiz is not found. Actualy I modified it a little to prevent false negative detection due to wrong geometry (those "== 22"). Luckily it should be working better now.

**Comment by hotice** [comment]
Yes, Unity in Ubuntu 12.04 allowed white-listing apps.

**Comment by karas84** [comment]
@hotice With the last git I silenced that error (it was quite useless after all) and introduced some output information that might be useful for debugging. Could you give it I try for me on 12.04? If it's trivial to fix I might take it into consideration, otherwise I think I'll skip that version since with white-listing there actually is a workaround for viber that works.

**Comment by hotice** [comment]
After some recent updates (to VirtualBox guest additions I think) Viber no longer works in my Ubuntu 12.04 machine so unfortunately I can't test it any more. I guess you can skip 12.04 since it does have the systray whitelist feature...

**Comment by karas84** [comment]
My thoughts exactly. I'm closing the issue then.
